[package]
name = "sf-wasm"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
  "MessageEvent",
  "RtcConfiguration",
  "RtcPeerConnection",
  "RtcDataChannel",
  "RtcDataChannelInit",
  "RtcDataChannelType",
  "RtcDataChannelEvent",
  "RtcIceCandidate",
  "RtcIceCandidateInit",
  "RtcIceConnectionState",
  "RtcIceGatheringState",
  "RtcSessionDescription",
  "RtcSessionDescriptionInit",
  "RtcPeerConnectionIceEvent",
  "RtcSdpType",
  "console",
  "Window",
  "HtmlTextAreaElement",
  "HtmlButtonElement",
  "HtmlInputElement",
  "HtmlDivElement",
  "HtmlDocument",
  "HtmlElement",
] }
js-sys = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-wasm-bindgen = "0.6.5"
