coverage:
  round: down
  precision: 2
  status:
    project:
      default:
        target: auto
        threshold: "1%"
        base: auto
        if_ci_failed: error
        informational: false
        only_pulls: false

comment:
  require_changes: false
  layout: "header, reach, diff, components, files, footer"

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        branches:
          - "!master"
  individual_components:
    - component_id: sf-metrics
      name: metrics
      paths:
        - sf-metrics/**
    - component_id: sf-webrtc
      name: webrtc
      paths:
        - sf-webrtc/**
