coverage:
  round: down
  precision: 2
  status:
    project:
      default:
        target: 90%
        threshold: "8%"
        base: auto
        if_ci_failed: error
        informational: false
        only_pulls: false

comment:
  require_changes: false
  layout: "header, reach, diff, components, files, footer"

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        branches:
          - "!master"
  individual_components:
    - component_id: sf-metrics
      name: metrics
      paths:
        - sf-metrics/**
    - component_id: sf-server
      name: server
      paths:
        - sf-server/**
    - component_id: sf-protocol
      name: protocol
      paths:
        - sf-protocol/**
    - component_id: sf-logging
      name: logging
      paths:
        - sf-logging/**
