services:
  node:
    container_name: node
    image: sfromens/sf-server:latest
    restart: always
    ports:
      - 8080:8080

  #coturn:
  #  container_name: coturn
  #  image: coturn/coturn
  #  restart: always
  #  ports:
  #    - 3478:3478/udp
  #    - 49152-65535:49152-65535/udp


volumes:
  ssl_data:
