[package]
name = "sf-node"
version = "0.1.0"
edition = "2024"

[dependencies]
multiaddr =  { version = "0.18" } 

libp2p-identity = { version = "0.2" }

sf-core = { path = "../sf-core" }

[lints]
workspace = true
