// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct KeepAliveRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct KeepAliveResponse {}
