[target.wasm32-unknown-unknown]
rustflags = [
  '--cfg',
  'getrandom_backend="wasm_js"',
  '-C',
  'debuginfo=2',
  '--cfg=web_sys_unstable_apis',
]
[build]
#target-dir = "target"
#target = "wasm32-unknown-unknown"
