[package]
name = "sf-peer-id"
version = "0.1.0"
edition = "2024"

[dependencies]

[features]
default = ["std"]
std = []

[package.metadata.docs.rs]
all-features = true

[lints.rust.unexpected_cfgs]
level = "deny"
check-cfg = ['cfg(coverage)', 'cfg(coverage_nightly)']
